language: elixir
elixir: 1.3.3
otp_release: 19.1
sudo: false
addons:
  postgresql: '9.4'
script:
- MIX_ENV=test mix ecto.create
- mix test --include integration
- MIX_ENV=test mix run priv/repo/seeds.exs
- git clone https://github.com/hexpm/hex ../hex && cd ../hex && mix deps.get && mix
  test --include integration
notifications:
  recipients:
  - eric.meadows.jonsson@gmail.com
  slack:
    secure: D21dsphy22i/G+yujf1V4f2x9pnbmTr2BkZv3nifXggTXY+ObItQ2MM/j9AoObdusbV63eSpvBZTIfX/oe7DQjN8hHBc/aILMZMLq7gKpOCTLtWIVvS9vNkyLa33EWwF/CsMiYQh377vye8a7cvORlkPmf+rNV//E9mbpuIWzBI=
